# Font
font_family      JetBrainsMono Nerd Font
font_size        11

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Window
window_padding_width 8

# Performance
confirm_os_window_close 0
enable_audio_bell no
allow_remote_control yes

# Scrollback
scrollback_lines 50000

# Selection
copy_on_select yes

# Mouse
hide_window_decorations no

# Theme
include current-theme.conf
